language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
#  - "3.4"
install:
  - pip install pytest
  - pip install pytest-flake8
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - pytest --flake8 --cov=slider/ --cache-clear
after_success:
  - coveralls
